# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Beñat Espiña <benatespina@gmail.com>
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

sylius_shop_api:
    resource: "@ShopApiPlugin/Resources/config/routing.yml"
