# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017 LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Beñat Espiña <benatespina@gmail.com>
# @author Gorka Laucirica <gorka.lauzirika@gmail.com>

app_homepage:
    path: /
    defaults:
        _controller: "app.http_action.home:__invoke"

app_file_upload:
    path: /file-upload
    defaults:
        _controller: "app.http_action.file_upload:__invoke"
    methods:
        - POST

app_file_gallery:
    path: /file-gallery
    defaults:
        _controller: "app.http_action.file_gallery:__invoke"
    methods:
        - GET
