# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

lin3s_distribution:
    webpack:
        manifest_path: "%env(ASSETS_MANIFEST_PATH)%"
        public_js_path: "%env(ASSETS_PUBLIC_JS_PATH)%"
        public_css_path: "%env(ASSETS_PUBLIC_CSS_PATH)%"
